# This workflow deploys a Vite-based React project to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 

      - name: Install Dependencies for "portfolio"
        run: |
          cd portfolio  # Change to the "portfolio" subdirectory
          npm install

      - name: Build
        run: npm run build  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/dist 

